{{- if not .Values.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "obs-playground.expressClaimName" . }}
  labels:
    {{- include "obs-playground.labels" . | nindent 4 }}
    app.kubernetes.io/component: express
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
{{- end }}
