/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as MealPlannerRouteImport } from './routes/meal-planner'
import { Route as BatchNutritionRouteImport } from './routes/batch-nutrition'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as RecipesCompareRouteImport } from './routes/recipes/compare'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as TestingErrorsRouteRouteImport } from './routes/testing/errors/route'
import { Route as TestingErrorsIndexRouteImport } from './routes/testing/errors/index'
import { Route as RecipesIdIndexRouteImport } from './routes/recipes/$id/index'
import { Route as TestingFormsBrokenCreateRouteImport } from './routes/testing/forms/broken-create'
import { Route as TestingErrorsTimeoutRouteImport } from './routes/testing/errors/timeout'
import { Route as TestingErrorsSuspenseErrorRouteImport } from './routes/testing/errors/suspense-error'
import { Route as TestingErrorsPartialFailureRouteImport } from './routes/testing/errors/partial-failure'
import { Route as TestingErrorsNotFoundRouteImport } from './routes/testing/errors/not-found'
import { Route as TestingErrorsNestedSuspenseRouteImport } from './routes/testing/errors/nested-suspense'
import { Route as TestingErrorsGraphqlErrorRouteImport } from './routes/testing/errors/graphql-error'
import { Route as TestingErrorsExpressErrorRouteImport } from './routes/testing/errors/express-error'
import { Route as TestingErrors500RouteImport } from './routes/testing/errors/500'
import { Route as TestingClientBrokenMutationRouteImport } from './routes/testing/client/broken-mutation'
import { Route as TestingClientBrokenApiRouteImport } from './routes/testing/client/broken-api'
import { Route as RecipesIdWithCostRouteImport } from './routes/recipes/$id/with-cost'
import { Route as RecipesIdNutritionRouteImport } from './routes/recipes/$id/nutrition'
import { Route as RecipesIdFullRouteImport } from './routes/recipes/$id/full'
import { Route as RecipesIdEditRouteImport } from './routes/recipes/$id/edit'

const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlannerRoute = MealPlannerRouteImport.update({
  id: '/meal-planner',
  path: '/meal-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchNutritionRoute = BatchNutritionRouteImport.update({
  id: '/batch-nutrition',
  path: '/batch-nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesCompareRoute = RecipesCompareRouteImport.update({
  id: '/recipes/compare',
  path: '/recipes/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingErrorsRouteRoute = TestingErrorsRouteRouteImport.update({
  id: '/testing/errors',
  path: '/testing/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingErrorsIndexRoute = TestingErrorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestingErrorsRouteRoute,
} as any)
const RecipesIdIndexRoute = RecipesIdIndexRouteImport.update({
  id: '/recipes/$id/',
  path: '/recipes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingFormsBrokenCreateRoute =
  TestingFormsBrokenCreateRouteImport.update({
    id: '/testing/forms/broken-create',
    path: '/testing/forms/broken-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestingErrorsTimeoutRoute = TestingErrorsTimeoutRouteImport.update({
  id: '/timeout',
  path: '/timeout',
  getParentRoute: () => TestingErrorsRouteRoute,
} as any)
const TestingErrorsSuspenseErrorRoute =
  TestingErrorsSuspenseErrorRouteImport.update({
    id: '/suspense-error',
    path: '/suspense-error',
    getParentRoute: () => TestingErrorsRouteRoute,
  } as any)
const TestingErrorsPartialFailureRoute =
  TestingErrorsPartialFailureRouteImport.update({
    id: '/partial-failure',
    path: '/partial-failure',
    getParentRoute: () => TestingErrorsRouteRoute,
  } as any)
const TestingErrorsNotFoundRoute = TestingErrorsNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => TestingErrorsRouteRoute,
} as any)
const TestingErrorsNestedSuspenseRoute =
  TestingErrorsNestedSuspenseRouteImport.update({
    id: '/nested-suspense',
    path: '/nested-suspense',
    getParentRoute: () => TestingErrorsRouteRoute,
  } as any)
const TestingErrorsGraphqlErrorRoute =
  TestingErrorsGraphqlErrorRouteImport.update({
    id: '/graphql-error',
    path: '/graphql-error',
    getParentRoute: () => TestingErrorsRouteRoute,
  } as any)
const TestingErrorsExpressErrorRoute =
  TestingErrorsExpressErrorRouteImport.update({
    id: '/express-error',
    path: '/express-error',
    getParentRoute: () => TestingErrorsRouteRoute,
  } as any)
const TestingErrors500Route = TestingErrors500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => TestingErrorsRouteRoute,
} as any)
const TestingClientBrokenMutationRoute =
  TestingClientBrokenMutationRouteImport.update({
    id: '/testing/client/broken-mutation',
    path: '/testing/client/broken-mutation',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestingClientBrokenApiRoute = TestingClientBrokenApiRouteImport.update({
  id: '/testing/client/broken-api',
  path: '/testing/client/broken-api',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdWithCostRoute = RecipesIdWithCostRouteImport.update({
  id: '/recipes/$id/with-cost',
  path: '/recipes/$id/with-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdNutritionRoute = RecipesIdNutritionRouteImport.update({
  id: '/recipes/$id/nutrition',
  path: '/recipes/$id/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdFullRoute = RecipesIdFullRouteImport.update({
  id: '/recipes/$id/full',
  path: '/recipes/$id/full',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdEditRoute = RecipesIdEditRouteImport.update({
  id: '/recipes/$id/edit',
  path: '/recipes/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batch-nutrition': typeof BatchNutritionRoute
  '/meal-planner': typeof MealPlannerRoute
  '/shopping-list': typeof ShoppingListRoute
  '/testing/errors': typeof TestingErrorsRouteRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/recipes/compare': typeof RecipesCompareRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/recipes/$id/full': typeof RecipesIdFullRoute
  '/recipes/$id/nutrition': typeof RecipesIdNutritionRoute
  '/recipes/$id/with-cost': typeof RecipesIdWithCostRoute
  '/testing/client/broken-api': typeof TestingClientBrokenApiRoute
  '/testing/client/broken-mutation': typeof TestingClientBrokenMutationRoute
  '/testing/errors/500': typeof TestingErrors500Route
  '/testing/errors/express-error': typeof TestingErrorsExpressErrorRoute
  '/testing/errors/graphql-error': typeof TestingErrorsGraphqlErrorRoute
  '/testing/errors/nested-suspense': typeof TestingErrorsNestedSuspenseRoute
  '/testing/errors/not-found': typeof TestingErrorsNotFoundRoute
  '/testing/errors/partial-failure': typeof TestingErrorsPartialFailureRoute
  '/testing/errors/suspense-error': typeof TestingErrorsSuspenseErrorRoute
  '/testing/errors/timeout': typeof TestingErrorsTimeoutRoute
  '/testing/forms/broken-create': typeof TestingFormsBrokenCreateRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
  '/testing/errors/': typeof TestingErrorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batch-nutrition': typeof BatchNutritionRoute
  '/meal-planner': typeof MealPlannerRoute
  '/shopping-list': typeof ShoppingListRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/recipes/compare': typeof RecipesCompareRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/recipes/$id/full': typeof RecipesIdFullRoute
  '/recipes/$id/nutrition': typeof RecipesIdNutritionRoute
  '/recipes/$id/with-cost': typeof RecipesIdWithCostRoute
  '/testing/client/broken-api': typeof TestingClientBrokenApiRoute
  '/testing/client/broken-mutation': typeof TestingClientBrokenMutationRoute
  '/testing/errors/500': typeof TestingErrors500Route
  '/testing/errors/express-error': typeof TestingErrorsExpressErrorRoute
  '/testing/errors/graphql-error': typeof TestingErrorsGraphqlErrorRoute
  '/testing/errors/nested-suspense': typeof TestingErrorsNestedSuspenseRoute
  '/testing/errors/not-found': typeof TestingErrorsNotFoundRoute
  '/testing/errors/partial-failure': typeof TestingErrorsPartialFailureRoute
  '/testing/errors/suspense-error': typeof TestingErrorsSuspenseErrorRoute
  '/testing/errors/timeout': typeof TestingErrorsTimeoutRoute
  '/testing/forms/broken-create': typeof TestingFormsBrokenCreateRoute
  '/recipes/$id': typeof RecipesIdIndexRoute
  '/testing/errors': typeof TestingErrorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batch-nutrition': typeof BatchNutritionRoute
  '/meal-planner': typeof MealPlannerRoute
  '/shopping-list': typeof ShoppingListRoute
  '/testing/errors': typeof TestingErrorsRouteRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/recipes/compare': typeof RecipesCompareRoute
  '/recipes/new': typeof RecipesNewRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/recipes/$id/full': typeof RecipesIdFullRoute
  '/recipes/$id/nutrition': typeof RecipesIdNutritionRoute
  '/recipes/$id/with-cost': typeof RecipesIdWithCostRoute
  '/testing/client/broken-api': typeof TestingClientBrokenApiRoute
  '/testing/client/broken-mutation': typeof TestingClientBrokenMutationRoute
  '/testing/errors/500': typeof TestingErrors500Route
  '/testing/errors/express-error': typeof TestingErrorsExpressErrorRoute
  '/testing/errors/graphql-error': typeof TestingErrorsGraphqlErrorRoute
  '/testing/errors/nested-suspense': typeof TestingErrorsNestedSuspenseRoute
  '/testing/errors/not-found': typeof TestingErrorsNotFoundRoute
  '/testing/errors/partial-failure': typeof TestingErrorsPartialFailureRoute
  '/testing/errors/suspense-error': typeof TestingErrorsSuspenseErrorRoute
  '/testing/errors/timeout': typeof TestingErrorsTimeoutRoute
  '/testing/forms/broken-create': typeof TestingFormsBrokenCreateRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
  '/testing/errors/': typeof TestingErrorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batch-nutrition'
    | '/meal-planner'
    | '/shopping-list'
    | '/testing/errors'
    | '/categories/$slug'
    | '/recipes/compare'
    | '/recipes/new'
    | '/recipes/$id/edit'
    | '/recipes/$id/full'
    | '/recipes/$id/nutrition'
    | '/recipes/$id/with-cost'
    | '/testing/client/broken-api'
    | '/testing/client/broken-mutation'
    | '/testing/errors/500'
    | '/testing/errors/express-error'
    | '/testing/errors/graphql-error'
    | '/testing/errors/nested-suspense'
    | '/testing/errors/not-found'
    | '/testing/errors/partial-failure'
    | '/testing/errors/suspense-error'
    | '/testing/errors/timeout'
    | '/testing/forms/broken-create'
    | '/recipes/$id/'
    | '/testing/errors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batch-nutrition'
    | '/meal-planner'
    | '/shopping-list'
    | '/categories/$slug'
    | '/recipes/compare'
    | '/recipes/new'
    | '/recipes/$id/edit'
    | '/recipes/$id/full'
    | '/recipes/$id/nutrition'
    | '/recipes/$id/with-cost'
    | '/testing/client/broken-api'
    | '/testing/client/broken-mutation'
    | '/testing/errors/500'
    | '/testing/errors/express-error'
    | '/testing/errors/graphql-error'
    | '/testing/errors/nested-suspense'
    | '/testing/errors/not-found'
    | '/testing/errors/partial-failure'
    | '/testing/errors/suspense-error'
    | '/testing/errors/timeout'
    | '/testing/forms/broken-create'
    | '/recipes/$id'
    | '/testing/errors'
  id:
    | '__root__'
    | '/'
    | '/batch-nutrition'
    | '/meal-planner'
    | '/shopping-list'
    | '/testing/errors'
    | '/categories/$slug'
    | '/recipes/compare'
    | '/recipes/new'
    | '/recipes/$id/edit'
    | '/recipes/$id/full'
    | '/recipes/$id/nutrition'
    | '/recipes/$id/with-cost'
    | '/testing/client/broken-api'
    | '/testing/client/broken-mutation'
    | '/testing/errors/500'
    | '/testing/errors/express-error'
    | '/testing/errors/graphql-error'
    | '/testing/errors/nested-suspense'
    | '/testing/errors/not-found'
    | '/testing/errors/partial-failure'
    | '/testing/errors/suspense-error'
    | '/testing/errors/timeout'
    | '/testing/forms/broken-create'
    | '/recipes/$id/'
    | '/testing/errors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchNutritionRoute: typeof BatchNutritionRoute
  MealPlannerRoute: typeof MealPlannerRoute
  ShoppingListRoute: typeof ShoppingListRoute
  TestingErrorsRouteRoute: typeof TestingErrorsRouteRouteWithChildren
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  RecipesCompareRoute: typeof RecipesCompareRoute
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesIdEditRoute: typeof RecipesIdEditRoute
  RecipesIdFullRoute: typeof RecipesIdFullRoute
  RecipesIdNutritionRoute: typeof RecipesIdNutritionRoute
  RecipesIdWithCostRoute: typeof RecipesIdWithCostRoute
  TestingClientBrokenApiRoute: typeof TestingClientBrokenApiRoute
  TestingClientBrokenMutationRoute: typeof TestingClientBrokenMutationRoute
  TestingFormsBrokenCreateRoute: typeof TestingFormsBrokenCreateRoute
  RecipesIdIndexRoute: typeof RecipesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-planner': {
      id: '/meal-planner'
      path: '/meal-planner'
      fullPath: '/meal-planner'
      preLoaderRoute: typeof MealPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-nutrition': {
      id: '/batch-nutrition'
      path: '/batch-nutrition'
      fullPath: '/batch-nutrition'
      preLoaderRoute: typeof BatchNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/compare': {
      id: '/recipes/compare'
      path: '/recipes/compare'
      fullPath: '/recipes/compare'
      preLoaderRoute: typeof RecipesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing/errors': {
      id: '/testing/errors'
      path: '/testing/errors'
      fullPath: '/testing/errors'
      preLoaderRoute: typeof TestingErrorsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing/errors/': {
      id: '/testing/errors/'
      path: '/'
      fullPath: '/testing/errors/'
      preLoaderRoute: typeof TestingErrorsIndexRouteImport
      parentRoute: typeof TestingErrorsRouteRoute
    }
    '/recipes/$id/': {
      id: '/recipes/$id/'
      path: '/recipes/$id'
      fullPath: '/recipes/$id/'
      preLoaderRoute: typeof RecipesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing/forms/broken-create': {
      id: '/testing/forms/broken-create'
      path: '/testing/forms/broken-create'
      fullPath: '/testing/forms/broken-create'
      preLoaderRoute: typeof TestingFormsBrokenCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing/errors/timeout': {
      id: '/testing/errors/timeout'
      path: '/timeout'
      fullPath: '/testing/errors/timeout'
      preLoaderRoute: typeof TestingErrorsTimeoutRouteImport
      parentRoute: typeof TestingErrorsRouteRoute
    }
    '/testing/errors/suspense-error': {
      id: '/testing/errors/suspense-error'
      path: '/suspense-error'
      fullPath: '/testing/errors/suspense-error'
      preLoaderRoute: typeof TestingErrorsSuspenseErrorRouteImport
      parentRoute: typeof TestingErrorsRouteRoute
    }
    '/testing/errors/partial-failure': {
      id: '/testing/errors/partial-failure'
      path: '/partial-failure'
      fullPath: '/testing/errors/partial-failure'
      preLoaderRoute: typeof TestingErrorsPartialFailureRouteImport
      parentRoute: typeof TestingErrorsRouteRoute
    }
    '/testing/errors/not-found': {
      id: '/testing/errors/not-found'
      path: '/not-found'
      fullPath: '/testing/errors/not-found'
      preLoaderRoute: typeof TestingErrorsNotFoundRouteImport
      parentRoute: typeof TestingErrorsRouteRoute
    }
    '/testing/errors/nested-suspense': {
      id: '/testing/errors/nested-suspense'
      path: '/nested-suspense'
      fullPath: '/testing/errors/nested-suspense'
      preLoaderRoute: typeof TestingErrorsNestedSuspenseRouteImport
      parentRoute: typeof TestingErrorsRouteRoute
    }
    '/testing/errors/graphql-error': {
      id: '/testing/errors/graphql-error'
      path: '/graphql-error'
      fullPath: '/testing/errors/graphql-error'
      preLoaderRoute: typeof TestingErrorsGraphqlErrorRouteImport
      parentRoute: typeof TestingErrorsRouteRoute
    }
    '/testing/errors/express-error': {
      id: '/testing/errors/express-error'
      path: '/express-error'
      fullPath: '/testing/errors/express-error'
      preLoaderRoute: typeof TestingErrorsExpressErrorRouteImport
      parentRoute: typeof TestingErrorsRouteRoute
    }
    '/testing/errors/500': {
      id: '/testing/errors/500'
      path: '/500'
      fullPath: '/testing/errors/500'
      preLoaderRoute: typeof TestingErrors500RouteImport
      parentRoute: typeof TestingErrorsRouteRoute
    }
    '/testing/client/broken-mutation': {
      id: '/testing/client/broken-mutation'
      path: '/testing/client/broken-mutation'
      fullPath: '/testing/client/broken-mutation'
      preLoaderRoute: typeof TestingClientBrokenMutationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing/client/broken-api': {
      id: '/testing/client/broken-api'
      path: '/testing/client/broken-api'
      fullPath: '/testing/client/broken-api'
      preLoaderRoute: typeof TestingClientBrokenApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/with-cost': {
      id: '/recipes/$id/with-cost'
      path: '/recipes/$id/with-cost'
      fullPath: '/recipes/$id/with-cost'
      preLoaderRoute: typeof RecipesIdWithCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/nutrition': {
      id: '/recipes/$id/nutrition'
      path: '/recipes/$id/nutrition'
      fullPath: '/recipes/$id/nutrition'
      preLoaderRoute: typeof RecipesIdNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/full': {
      id: '/recipes/$id/full'
      path: '/recipes/$id/full'
      fullPath: '/recipes/$id/full'
      preLoaderRoute: typeof RecipesIdFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/edit': {
      id: '/recipes/$id/edit'
      path: '/recipes/$id/edit'
      fullPath: '/recipes/$id/edit'
      preLoaderRoute: typeof RecipesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TestingErrorsRouteRouteChildren {
  TestingErrors500Route: typeof TestingErrors500Route
  TestingErrorsExpressErrorRoute: typeof TestingErrorsExpressErrorRoute
  TestingErrorsGraphqlErrorRoute: typeof TestingErrorsGraphqlErrorRoute
  TestingErrorsNestedSuspenseRoute: typeof TestingErrorsNestedSuspenseRoute
  TestingErrorsNotFoundRoute: typeof TestingErrorsNotFoundRoute
  TestingErrorsPartialFailureRoute: typeof TestingErrorsPartialFailureRoute
  TestingErrorsSuspenseErrorRoute: typeof TestingErrorsSuspenseErrorRoute
  TestingErrorsTimeoutRoute: typeof TestingErrorsTimeoutRoute
  TestingErrorsIndexRoute: typeof TestingErrorsIndexRoute
}

const TestingErrorsRouteRouteChildren: TestingErrorsRouteRouteChildren = {
  TestingErrors500Route: TestingErrors500Route,
  TestingErrorsExpressErrorRoute: TestingErrorsExpressErrorRoute,
  TestingErrorsGraphqlErrorRoute: TestingErrorsGraphqlErrorRoute,
  TestingErrorsNestedSuspenseRoute: TestingErrorsNestedSuspenseRoute,
  TestingErrorsNotFoundRoute: TestingErrorsNotFoundRoute,
  TestingErrorsPartialFailureRoute: TestingErrorsPartialFailureRoute,
  TestingErrorsSuspenseErrorRoute: TestingErrorsSuspenseErrorRoute,
  TestingErrorsTimeoutRoute: TestingErrorsTimeoutRoute,
  TestingErrorsIndexRoute: TestingErrorsIndexRoute,
}

const TestingErrorsRouteRouteWithChildren =
  TestingErrorsRouteRoute._addFileChildren(TestingErrorsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchNutritionRoute: BatchNutritionRoute,
  MealPlannerRoute: MealPlannerRoute,
  ShoppingListRoute: ShoppingListRoute,
  TestingErrorsRouteRoute: TestingErrorsRouteRouteWithChildren,
  CategoriesSlugRoute: CategoriesSlugRoute,
  RecipesCompareRoute: RecipesCompareRoute,
  RecipesNewRoute: RecipesNewRoute,
  RecipesIdEditRoute: RecipesIdEditRoute,
  RecipesIdFullRoute: RecipesIdFullRoute,
  RecipesIdNutritionRoute: RecipesIdNutritionRoute,
  RecipesIdWithCostRoute: RecipesIdWithCostRoute,
  TestingClientBrokenApiRoute: TestingClientBrokenApiRoute,
  TestingClientBrokenMutationRoute: TestingClientBrokenMutationRoute,
  TestingFormsBrokenCreateRoute: TestingFormsBrokenCreateRoute,
  RecipesIdIndexRoute: RecipesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
