import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import * as Sentry from "@sentry/nextjs";
import MyStatsig from "./my-statsig";
import SentryInit from "./sentry-init";

// Force all pages to be dynamically rendered at runtime
// This ensures GraphQL/API requests happen during runtime for proper tracing
export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Enable distributed tracing for App Router on Next.js 14+
// This connects client-side traces with server-side OTEL traces
export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
    other: Sentry.getTraceData() as Record<string, string>,
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SentryInit />
        <MyStatsig>{children}</MyStatsig>
      </body>
    </html>
  );
}
