name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

permissions:
  contents: read

concurrency: terraform-infra

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  TF_WORKSPACE: ${{ vars.TF_WORKSPACE_INFRA }}
  CONFIG_DIRECTORY: ./infra

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Terraform configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create apply run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          message: "Infra apply from GitHub Actions for ${{ github.sha }}"

      - name: Confirm apply run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        id: apply
        if: fromJSON(steps.create-run.outputs.payload).data.attributes.actions.IsConfirmable
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Confirmed from GitHub Actions for ${{ github.sha }}"
